import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header className="navbar bg-primary justify-between">
          <Link href="/">
              <h1 className="text-3xl font-semibold text-primary-content hover:text-secondary">Code Blocks</h1>
          </Link>
          <Link
              href="/blocks/create"
              className="btn btn-accent"
          >
              + Create Block
          </Link>
      </header>
      <main>
          {children}
      </main>
      </body>
    </html>
  );
}
